### ISSUE TITLE
Cannot compile with -O2 optimizations

### ISSUE THREAD

**Issue by vlapse** [cbuchner1/ccminer#15]
Hi.

I cannot compile newest ccminer with -O2 or -O3 optimizations....

```
/opt/cuda/bin/nvcc -O2 -I . -Xptxas "-abi=no -v" -gencode=arch=compute_20,code=\"sm_20,compute_20\" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" --maxrregcount=80 --ptxas-options=-v  -o cuda_groestlcoin.o -c cuda_groestlcoin.cu
groestl_functions_quad.cu(258): error: identifier "__shfl" is undefined

groestl_functions_quad.cu(263): error: identifier "__shfl" is undefined

groestl_functions_quad.cu(268): error: identifier "__shfl" is undefined

bitslice_transformations_quad.cu(8): error: identifier "__shfl" is undefined

bitslice_transformations_quad.cu(414): error: identifier "__shfl" is undefined

5 errors detected in the compilation of "/tmp/tmpxft_0000495c_00000000-13_cuda_groestlcoin.compute_20.cpp1.ii".
```

**Comment by cbuchner1** [comment]
remove the compute_20,code=sm,compute_20 part

I wonder how it got in there in the first place as ccMiner does not and
will not support Compute 2.0 devices at this point.

2014-06-14 20:27 GMT+02:00 helllgast notifications@github.com:

**Comment by cbuchner1** [comment]
if you look at Makefile.am in the current github master branch you won't
find any mention of Compute 2.0

https://github.com/cbuchner1/ccminer/blob/master/Makefile.am

did you run ./autogen.sh also?

**Comment by vlapse** [comment]
I didn't run ./autogen.sh, my fault sorry...
