### ISSUE TITLE
cc miner problem on my linux

### ISSUE THREAD

**Issue by waqasaqb** [cbuchner1/ccminer#60]
hi
i am new to github i want to use your ccminer in linux 16.04 and gpu NVIDIA® Tesla® P100 GPUs
please give me your ccminer with my gpu
and i have the eror on my linux

make all-recursive
make[1]: Entering directory '/home/waqas/ccminer'
Making all in compat
make[2]: Entering directory '/home/waqas/ccminer/compat'
make[3]: Entering directory '/home/waqas/ccminer/compat'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/waqas/ccminer/compat'
make[2]: Leaving directory '/home/waqas/ccminer/compat'
make[2]: Entering directory '/home/waqas/ccminer'
nvcc -gencode=arch=compute_50,code="sm_50,compute_50" -gencode=arch=compute_52,code="sm_52,compute_52" -I/usr/l
ocal/cuda/include -I. --ptxas-options="-v" --maxrregcount=128 -o equi/cuda_equi.o -c equi/cuda_equi.cu
/bin/bash: nvcc: command not found
Makefile:2669: recipe for target 'equi/cuda_equi.o' failed
make[2]: *** [equi/cuda_equi.o] Error 127
make[2]: Leaving directory '/home/waqas/ccminer'
Makefile:2201: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/waqas/ccminer'
Makefile:654: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by joo9lao1IeVeetai3huw** [comment]
The program 'nvcc' is currently not installed. You can install it by typing:
sudo apt install nvidia-cuda-toolkit

or

take a look here: https://stackoverflow.com/questions/13519459/nvcc-command-not-found or https://askubuntu.com/a/428235

and

did you install nvidias CUDA Toolkit ?
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1604 

Good Luck

**Comment by waqasaqb** [comment]
hi and thanks for helping my problem is solved.
